# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Homelab:
    - Portainer:
        href: http://home-labv1/
        description: Container Mgmt

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎

