# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
#    provider: google # Uncomment to use Google instead of DuckDuckGo
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short